# ─────────────────────────────────────────────────────────────────
# models/hcp.py – Healthcare Professional (HCP) ORM model
#
# Represents a doctor / nurse / pharmacist that a sales rep visits.
# One HCP can have many Interactions (one-to-many relationship).
# ─────────────────────────────────────────────────────────────────

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class HCP(Base):
    """
    Healthcare Professional entity.

    Columns
    -------
    id            : UUID primary key, auto-generated by PostgreSQL.
    name          : Full name of the HCP (required).
    specialty     : Medical specialty (e.g. Cardiology, Oncology).
    hospital      : Hospital / clinic affiliation.
    email         : Unique contact email (optional).
    phone         : Contact phone number (optional).
    territory     : Sales territory the HCP belongs to.
    created_at    : Record creation timestamp (UTC, server-side default).
    updated_at    : Auto-updated on every row modification.
    interactions  : Back-reference to all Interaction records for this HCP.
    """

    __tablename__ = "hcps"

    # ── Primary key ───────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    # ── Required fields ───────────────────────────────────────────
    name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # ── Optional contact / classification fields ──────────────────
    specialty: Mapped[str | None] = mapped_column(String(100), nullable=True)
    hospital: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email: Mapped[str | None] = mapped_column(
        String(255), nullable=True, unique=True, index=True
    )
    phone: Mapped[str | None] = mapped_column(String(30), nullable=True)
    territory: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # ── Audit timestamps ──────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        default=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ─────────────────────────────────────────────
    # lazy="select" defers loading until accessed (safe with async via selectin)
    interactions: Mapped[list["Interaction"]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Interaction",
        back_populates="hcp",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<HCP id={self.id} name='{self.name}'>"
